Fixed args_parse
tezkerek/disk-analyzer pull request #11
Opened 2022-12-23 19:11 UTC by andlft

2022-12-24 09:09 UTC, Qmpzlawasd commented on src/client/arg_parse.h
> +
format code

2022-12-24 09:11 UTC, Qmpzlawasd commented on src/client/arg_parse.c
> +    return ret;
remove

2022-12-24 09:11 UTC, Qmpzlawasd commented on src/client/arg_parse.c
> +        exit(EXIT_FAILURE);
return NULL; ?

2022-12-24 09:12 UTC, Qmpzlawasd commented on src/client/arg_parse.c
>  }
remove exit

2022-12-24 18:56 UTC, tezkerek requested changes

2022-12-24 18:56 UTC, tezkerek commented on src/client/arg_parse.c
> +    "-p, --print <id> print analysis report for those tasks that are done\n";
Could be static, maybe moved to header.
Indent, align quotes on same column.

2022-12-24 18:56 UTC, tezkerek commented on src/client/arg_parse.c
> +            ret->cmd = 2;
Use `CMD_SUSPEND` from ipc.h.
Same for all other assignments.

2022-12-24 18:56 UTC, tezkerek commented on src/client/arg_parse.c
> +    ret = malloc(sizeof(struct return_struct));
Usually we malloc in the caller and pass a pointer as an `out` parameter. Then you can use the return value as an exit code (e.g. `-1` for error).

2022-12-24 18:56 UTC, tezkerek commented on src/client/arg_parse.c
> +        }
I would just validate the args in each `case`, i.e. if `cmd` is already set then exit with failure; in `case 'p'` check if `cmd` is `CMD_ADD` and if it's not then `cmd = CMD_PRINT`, otherwise set `priority` to the value etc.

2022-12-24 18:56 UTC, tezkerek commented on src/client/arg_parse.h
> +#define CLIENT_HEADER
Should be `ARG_PARSE_HEADER`.

2022-12-24 18:56 UTC, tezkerek commented on src/client/arg_parse.c
>              strcpy(path, optarg);
Is a copy necessary here?

2022-12-24 18:56 UTC, tezkerek commented on src/client/arg_parse.h
> +		char *payload;
Arg parsing shouldn't be aware of IPC stuff like payload.

The arg values are either a path for `CMD_ADD` or a job ID for the other commands. I propose we use a union for the possible values, and have `cmd` as the discriminator.
```c
union {
    int64_t job_id;
    struct { int64_t path_len; char *path; };
};
```

2022-12-25 14:31 UTC, andlft commented on src/client/arg_parse.c
> +        }
I wouldn't. :crusulaugh:

2022-12-25 23:33 UTC, tezkerek requested changes
Much cleaner 👍🏻
Try `clang-format` to fix all the spacing.

2022-12-25 23:33 UTC, tezkerek commented on src/client/arg_parse.c
>          int this_option_optind = optind ? optind : 1;
Unused variable?

2022-12-25 23:33 UTC, tezkerek commented on src/client/arg_parse.c
> +            ret->priority = (int8_t)2;
`#define DEFAULT_PRIORITY 2` in header.

2022-12-25 23:33 UTC, tezkerek commented on src/client/arg_parse.h
> +};
Fix indentation

2022-12-25 23:33 UTC, tezkerek commented on src/client/arg_parse.c
> +            strcpy(ret->path, optarg);
Prefer `strncpy` against buffer overflow.

2022-12-25 23:33 UTC, tezkerek commented on src/client/arg_parse.c
> +                ret->job_id = atoi(optarg);
`job_id` is `int64_t`, so `atoll` should be used. But `strtoll` would be better for error handling.

Same for all other instances of `atoi`.

2022-12-25 23:33 UTC, tezkerek commented on src/client/arg_parse.h
> +struct return_struct {
Struct name is not suggestive. Something like `args` or `da_args` would work.

2022-12-26 10:36 UTC, tezkerek requested changes
One last thing

2022-12-26 10:36 UTC, tezkerek commented on src/client/arg_parse.c
> +            ret->path = malloc(path_len + 1);
Use `da_malloc` from `utils.h`

2023-01-03 17:45 UTC, tezkerek approved these changes

2023-01-03 17:47 UTC, merged