Handle cmd2
tezkerek/disk-analyzer pull request #12
Opened 2022-12-26 16:23 UTC by AdelaCorbeanu

2022-12-26 17:10 UTC, Qmpzlawasd commented on src/daemon/daemon.c
> +		last[job_count]->children[last[job_count]->number_subdir] = current;
`last[job_count]->number_subdir` starts form 1?

2022-12-28 20:23 UTC, Qmpzlawasd requested changes

2022-12-28 20:23 UTC, Qmpzlawasd commented on src/daemon/daemon.c
> +	jobs[job_count]->root = last[job_count];
useless malloc, it's just copying a pointer.

2022-12-29 21:47 UTC, tezkerek requested changes
Run `clang-format` or VS Code formatter.

2022-12-29 21:47 UTC, tezkerek commented on src/common/ipc.h
> +#define CMD_ADD     7
Revert

2022-12-29 21:47 UTC, tezkerek commented on src/daemon/daemon.c
>  struct Job job_history[MAX_THREADS];
`job_history` is unused?

2022-12-29 21:47 UTC, tezkerek commented on src/daemon/daemon.c
> +	char *aux = malloc(strlen(fpath) * sizeof(char) + 1);
`(strlen(fpath) + 1) * sizeof(*current->path)`
Same for the other 2.

2022-12-29 21:47 UTC, tezkerek commented on src/daemon/daemon.c
> +	int nopenfd = 20;  // ne gandim cat vrem sa punem
`static`

2022-12-29 21:47 UTC, tezkerek commented on src/daemon/daemon.c
> +	jobs[job_count] = malloc(sizeof(jobs[job_count]));
Shouldn't this be `sizeof(*jobs[job_count])`?

2022-12-29 21:47 UTC, tezkerek commented on src/client/client.c
> +
Revert

2022-12-29 21:47 UTC, tezkerek commented on src/daemon/daemon.c
> +		return errno;
Returning `int` in a `void*` function.

2023-01-03 17:17 UTC, tezkerek requested changes

2023-01-03 17:17 UTC, tezkerek commented on src/daemon/daemon.c
> +	if (!strcmp(fpath, last[job_count]->path)) return 0;
Why `job_count`? That always refers to the last job.

2023-01-03 17:17 UTC, tezkerek commented on src/daemon/daemon.c
>  static uint64_t job_count = 0;
This should be made thread-safe. Let's use [atomics](https://en.cppreference.com/w/c/atomic).

2023-01-03 17:17 UTC, tezkerek commented on src/daemon/daemon.c
> +struct Job *jobs[MAX_THREADS];
The daemon could receive two simultaneous commands for the same job. We'll probably need a lock for each job.

2023-01-03 17:17 UTC, tezkerek commented on src/daemon/daemon.c
> +		exit(EXIT_FAILURE);
Don't exit, return -1.

2023-01-05 14:21 UTC, tezkerek requested changes

2023-01-05 14:21 UTC, tezkerek commented on src/daemon/thread_utils.c
> +    int job_id = ((struct traverse_args *)args)->job_id;
`int64_t job_id`.
We should probably add a typedef for this.

2023-01-05 14:21 UTC, tezkerek commented on src/daemon/thread_utils.c
> +    fts_args[1] = NULL;
`char *fts_args[] = {path, NULL}`

2023-01-05 14:21 UTC, tezkerek commented on src/daemon/thread_utils.c
> +    new_directory->path = malloc((strlen(path) + 1) * sizeof(char));
`sizeof(*new_directory->path)`
Also use `da_malloc` everywhere.

2023-01-05 14:21 UTC, tezkerek commented on src/daemon/daemon.c
> +    // TODO: Mutex unlock?
Regarding locking, atomics seem pretty easy. In this situation you need https://en.cppreference.com/w/c/atomic/atomic_fetch_add.

2023-01-05 14:21 UTC, tezkerek commented on src/daemon/daemon.c
> +    struct traverse_args *args = malloc(sizeof(struct traverse_args));
`sizeof(*args)`

2023-01-05 14:21 UTC, tezkerek commented on src/daemon/thread_utils.c
> +    struct Directory *new_directory = malloc(sizeof(struct Directory));
`sizeof(*new_directory)`

2023-01-07 16:25 UTC, Qmpzlawasd requested changes

2023-01-07 16:25 UTC, Qmpzlawasd commented on src/daemon/thread_utils.c
> +        parent->children = realloc(parent->children, parent->children_capacity);
Manpage:
> void *realloc(void *ptr, size_t size);  
> The  realloc() function changes the size of the memory block pointed by ptr to size bytes.

Should be `realloc(parent->children, parent->children_capacity * sizeof(struct Directory *));`

2023-01-07 16:32 UTC, Qmpzlawasd requested changes

2023-01-07 16:32 UTC, Qmpzlawasd commented on src/daemon/thread_utils.c
> +        parent->children = realloc(parent->children, parent->children_capacity);
Should be `realloc(parent->children, parent->children_capacity * sizeof(struct Directory *));`

2023-01-10 21:43 UTC, tezkerek commented
Continued in #19.

2023-01-10 21:43 UTC, closed without merging